'use strict';

var styleInject_es = require('../../node_modules/style-inject/dist/style-inject.es.js');

var css_248z = ".primary {\n  background-color: #e07a5f; }\n\n.accent {\n  background-color: #81b29a; }\n\n.SearchBarWrapper {\n  display: flex;\n  flex-direction: column; }\n\n.searchLabel {\n  margin: 0rem 0rem 0rem 0.5rem;\n  color: rgba(61, 64, 91, 0.8); }\n\n.searchInput {\n  border: 0;\n  height: 2rem;\n  flex-grow: 1;\n  margin: 0;\n  padding: 0.5rem;\n  background-color: rgba(255, 255, 255, 0);\n  transition: 100ms all ease;\n  outline: 0; }\n\n.searchBox {\n  width: 100%;\n  display: flex;\n  flex-direction: row;\n  justify-content: space-between;\n  outline: 0; }\n\n.searchBoxOutline {\n  border: 0.2rem solid #3d405b;\n  border-radius: 3rem;\n  transition: 200ms all ease; }\n  .searchBoxOutline:focus::before, .searchBoxOutline:focus::after, .searchBoxOutline:focus-within, .searchBoxOutline:focus, .searchBoxOutline:focus-visible, .searchBoxOutline:active, .searchBoxOutline:hover {\n    border: 0.2rem solid #81b29a;\n    animation: borderColorsOutline 200ms linear forwards; }\n\n.searchBoxBottom {\n  border-top: 0;\n  border-left: 0;\n  border-right: 0;\n  border-bottom: 0.2rem solid #3d405b;\n  border-radius: 2px;\n  transition: 200ms all ease; }\n  .searchBoxBottom:focus-within {\n    border-bottom: 0.2rem solid #81b29a; }\n\n.submitButton {\n  border: 0;\n  margin: 0;\n  background-color: rgba(255, 255, 255, 0);\n  border: 0.12rem solid #e07a5f;\n  border-radius: 4rem;\n  margin: 0.3rem 1rem;\n  text-align: center;\n  color: #3d405b;\n  transition: 50ms all; }\n  .submitButton:hover {\n    background-color: #81b29a;\n    border: 0;\n    scale: 1.05;\n    color: #f4f1de; }\n\n@keyframes borderColorsOutline {\n  0% {\n    border-top-color: #3d405b;\n    border-right-color: #3d405b;\n    border-bottom-color: #3d405b;\n    border-left-color: #3d405b; }\n  33% {\n    border-top-width: 100%;\n    border-top-color: #3d405b;\n    border-right-color: #3d405b;\n    border-bottom-color: #81b29a;\n    border-left-color: #3d405b; }\n  66% {\n    border-top-color: #3d405b;\n    border-right-color: #81b29a;\n    border-bottom-color: #81b29a;\n    border-left-color: #81b29a; }\n  100% {\n    border-top-color: #81b29a;\n    border-right-color: #81b29a;\n    border-bottom-color: #81b29a;\n    border-left-color: #81b29a; } }\n";
styleInject_es(css_248z);

module.exports = css_248z;
//# sourceMappingURL=SearchBar.scss.js.map
